cli:
  app_directory: apps
  base_model: apps.utils.models.BaseModel
  module_path: apps
  template_directory: templates
  use_teams: false
default_context:
  _pegasus_version: 2024.11.3
  ai_chat_mode: llm
  ai_image_mode: multiple
  author_name: Matteo
  ci: github_actions
  css_framework: tailwind
  css_theme: default
  database: postgres
  deploy_platform: google_cloud_run
  description: The most amazing SaaS application the world has ever seen
  docker_setup: arm64
  domain_name: localhost:8000
  email: dev@duckma.com
  enable_github_login: n
  enable_google_login: y
  enable_twitter_login: n
  front_end_framework: react
  github_username: gazzumatteo
  include_static_files: y
  marketing_email_platform: none
  post_process: y
  project_name: Test Project
  project_slug: mg_saas_test_project
  python_package_manager: pip-tools
  standalone_front_end: none
  stripe_payment_mode: checkout
  subscription_billing_model: per_unit
  subscription_pricing_ui: stripe_hosted
  use_2fa: y
  use_admin_docs: y
  use_api_auth: y
  use_api_keys: y
  use_async_example: y
  use_cloud_media_storage: n
  use_dark_mode: y
  use_debug_toolbar: n
  use_docker: y
  use_ecommerce_example: n
  use_examples: y
  use_flowbite: y
  use_health_checks: y
  use_impersonation: y
  use_sentry: y
  use_shadcn: n
  use_subscriptions: y
  use_teams: n
  use_teams_example: n
  use_translations: y
  use_wagtail: y
